export const ACCESS_TOKEN_LOCAL_STORAGE_KEY = "ielts_tinder_admin_access_token";
export const TYPE_LISTENING_QUESTION = [
  "MULTIPLE_LISTENING",
  "SINGLE_LISTENING",
];
export const TYPE_READING_QUESTION = ["SENTENCE_READING", "PARAGRAPH_READING"];
